variables:
  buildConfiguration: 'Release'
trigger:
- master
pool:
  vmImage: 'windows-2019'
steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.2.100' 
- script: dotnet tool install -g dotnet-sonarscanner
  displayName: dotnet install sonarscanner
- script: dotnet sonarscanner begin /k:"cdemi_NewsletterCurator" /o:"cdemi-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(sonarLogin)" /d:sonar.projectVersion="$(Build.BuildNumber)""
  displayName: dotnet sonarscanner begin 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build
- script: dotnet test NewsletterCurator.HTMLScraper.Tests --no-build --no-restore --configuration $(buildConfiguration) --logger trx --collect "Code coverage"
  displayName: dotnet test
- script: dotnet sonarscanner end /d:sonar.login="$(sonarLogin)"
  displayName: dotnet sonarscanner end
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- script: dotnet publish --no-build --no-restore --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: dotnet publish
- task: PublishBuildArtifacts@1
  displayName: Publishing Artifacts
