# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to Dockerhub
      inputs:
        command: login
        containerRegistry: Dockerhub
    - task: Docker@2
      displayName: Build and Push an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/NewsletterCurator.Web/Dockerfile'
        repository: 'cdemi/NewsletterCurator'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          latest
          $(Build.BuildId)
